os:
  - linux
  
sudo: false

language: python

python:
  - 2.7
  - 3.2

before_install: 
  - easy_install Cython  
  - easy_install progressbar
  
install: python setup.py install
script: python setup.py test
